
spring:
#--------------------------charset--------------------------
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
#--------------------------Server--------------------------
  server:
    tomcat:
      uri-encoding: UTF-8
  datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/ntc-lite
      username: root
      password: root
      druid:
          # 初始连接数
          initial-size: 10
          # 最大连接池数量
          max-active: 100
          # 最小连接池数量
          min-idle: 10
          # 配置获取连接等待超时的时间
          max-wait: 60000
          # 打开PSCache，并且指定每个连接上PSCache的大小
          pool-prepared-statements: true
          max-pool-prepared-statement-per-connection-size: 20
          # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
          timeBetweenEvictionRunsMillis: 60000
          # 配置一个连接在池中最小生存的时间，单位是毫秒
          min-evictable-idle-time-millis: 300000
          validation-query: SELECT 1 FROM DUAL
          test-while-idle: true
          test-on-borrow: false
          test-on-return: false
          stat-view-servlet:
              enabled: true
              url-pattern: /druid/*
              allow: 127.0.0.1
              login-username: admin
              login-password: admin
          filter:
              stat:
                  log-slow-sql: true
                  slow-sql-millis: 1000
                  merge-sql: false
              wall:
                  config:
                      multi-statement-allow: true
  logging:
    level: debug
mybatis-plus:
  mapper-locations: classpath:mapper/*/*.xml
  type-aliases-package: com.mc.mfb.admin.entity
  #redis:
     #    host: localhost
     #    port: 6379
     #    timeout: 3000
     #    lettuce:
     #      pool:
     #        max-idle: 100
     #        min-idle: 10
     #        max-wait: 2000
server:
  port: 8088